name: Build and Push to GAR

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Authenticate with Google Cloud
      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      # Configure Docker to use GAR
      - name: Set up Docker
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # Build and push the image
      - name: Build and Push
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/etl-pipeline/etl-pipeline:latest .
          docker push us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/etl-pipeline/etl-pipeline:latest
